version: "3.2"

services:
  postgres:
    image: "postgres:11.2"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  python_service:
    container_name: python_service
    environment:
      - DB_PASS=test
      - DB_USER=test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python_docker_sample:/app/python_docker_sample
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    ports:
      - "8080:8080"
    depends_on:
    - postgres
  